facebook_app_id = ""
facebook_app_secret = ""
[dev]
topics = "all" # or ["a", "b", "c"]
created = "2022-06-01"
domain = "wsl"
cjid = ""
cjtoken = ""
twitter_consumer_key = ""
twitter_consumer_secret = ""
twitter_access_token_key = ""
twitter_access_token_secret = ""
twitter_handle = ""
facebook_page_id = ""
facebook_page_token = ""
