#!/usr/bin/env bash
#
NAMES=scraper,$SITES
IFS=,
DUPLOCKFILE=/tmp/.duplicacy_sites_lock
DUPBIN=dup

while true; do
    output=$(docker ps)
    for name in $NAMES; do
        ct=$(echo $output | grep $name)
        if [ "${ct/unhealthy/}" != "$ct" ]; then
            docker restart $name
        elif [ "${ct/Paused/}" != "$ct" ]; then
            if [ -e $DUPLOCKFILE ]; then
                if ! pgrep -x $DUPBIN; then
                    echo "Duplicacy lockfile found without backup process ($DUPBIN) running, removing lockfile."
                    docker unpause $name
                fi
            else
                docker unpause $name
            fi
        fi
    done
    sleep 60
done
