const stub_title* = "Lorem Ipsum"

const stub_article* = """


Lorem ipsum dolor sit amet, consectetur adipiscing elit. In mi lorem, porta a neque vitae, condimentum molestie lacus. Curabitur ornare mauris et facilisis eleifend. Duis malesuada, justo a placerat mollis, lorem magna congue magna, quis consequat massa est eu ante. Praesent lorem turpis, maximus sed justo et, lobortis tincidunt libero. Mauris egestas metus eget mi vulputate, eget ullamcorper augue mollis. Vivamus vestibulum in mi imperdiet imperdiet. Sed quis vestibulum ligula, eget aliquam velit. Quisque eu purus ligula. Maecenas placerat iaculis quam, sit amet laoreet ipsum auctor non. Phasellus rhoncus urna et viverra lobortis. Vestibulum hendrerit erat mi. Duis sit amet ex nec mi gravida placerat. Sed ut velit pharetra, sagittis risus sit amet, posuere eros. Ut malesuada euismod tellus, ut pretium felis scelerisque vel. Vestibulum consequat accumsan justo, quis aliquet velit.

Nam porttitor eget ante vitae porttitor. Phasellus nec nisi vitae dui pellentesque eleifend eu quis velit. Suspendisse auctor rutrum nisi, et vehicula ipsum. Praesent luctus, tellus ut vehicula vehicula, metus sem elementum leo, sed rhoncus metus turpis non ipsum. Nam tincidunt lacus id risus rhoncus elementum. Nunc sed orci id odio suscipit efficitur eget sollicitudin sem. Morbi urna dui, pharetra id aliquam id, porta a lorem. Morbi fringilla sagittis diam, ultricies bibendum ex ultrices eget. Sed non orci ut tortor venenatis dapibus quis a magna. Duis eleifend velit velit, id tempor quam commodo sit amet. Morbi feugiat augue a nunc tincidunt interdum. Interdum et malesuada fames ac ante ipsum primis in faucibus.

Quisque tristique purus sit amet elit rutrum vulputate. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean porta ante non lobortis sodales. Cras mattis orci blandit augue accumsan, et pretium massa sagittis. Praesent dui felis, suscipit faucibus interdum sit amet, facilisis vitae arcu. Nullam mollis fringilla porta. Nulla suscipit eu neque in egestas. Suspendisse ultrices, turpis ac cursus mattis, massa felis finibus ante, sed faucibus elit urna a nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam ac nulla eu augue feugiat gravida. Curabitur id nisi arcu. Quisque suscipit ex et leo egestas efficitur.

Phasellus pellentesque tellus lobortis neque suscipit, vel sollicitudin metus dapibus. Morbi dui neque, venenatis vitae tincidunt vitae, consectetur a justo. Ut malesuada, risus eget consectetur pulvinar, ante urna gravida diam, nec sagittis felis purus quis lorem. Ut vulputate lacinia pulvinar. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque a dignissim ante. Morbi est sapien, rutrum nec sem eget, porttitor malesuada ex. Aliquam erat volutpat. Donec mauris arcu, pulvinar suscipit placerat eget, tincidunt sit amet diam. Morbi fermentum neque quis arcu venenatis sodales.

Morbi nec eros sit amet elit egestas pharetra. Pellentesque ligula sapien, vehicula eget lobortis quis, sagittis suscipit ex. Praesent a tincidunt enim, eu consectetur libero. Curabitur tincidunt scelerisque venenatis. Proin quis felis varius ligula accumsan suscipit. Pellentesque gravida auctor nisi. Sed a vehicula turpis, sed gravida neque. Pellentesque tempus est dui, eget semper purus suscipit quis. Curabitur porta ullamcorper odio sit amet tempus. Cras in euismod lectus. Nullam fringilla auctor molestie. In vitae fringilla arcu. Ut in vestibulum lacus. Nulla et purus ut ligula blandit luctus.
"""
